### PR TITLE
Make this package modern

### PR DESCRIPTION
**Pull request by MCPE-PC**
* [x] Use `Buffer.alloc()` and `Buffer.from()` instead of `new Buffer()`
 * [x] Update dependencies
 * [ ] ~~Make test success~~
 * Increased `PATCH` version, due to Semantic Versioning. (But would not be compatible in older Node.js)
 * And so on... + Annoying commit messsges

And sorry, I forgot to run `npm test` before I submit a Pull Request, so I made you to wait for me.

### CODE REVIEW

**Comment by kmpm** [comment]
Good work so far... Have you found out why the tests fail?

**Comment by MCPE-PC** [comment]
@kmpm
1. `expect().to.deep` does not exist
2. I don't know why `response-4` does not match

**Comment by MCPE-PC** [comment]
I gave up viewing bin file. Done.

**Comment by MCPE-PC** [comment]
@kmpm Hmm... Please review this Pull Request

**Comment by kmpm** [comment]
It's failing the tests so I will not pull right now.
But working on a solution

**Comment by kmpm** [comment]
New version 1.0.0 published from work I had brewing in my own branch...

**Pull request closed without merging**
